import Head from "next/head";
import cx from "classnames";
import Link from "next/link";

import { Header } from "../Homepage/Header/Header";
import styles from "../../styles/Home.module.css";

interface ILayout {
    children: JSX.Element;
}

const Layout: React.FC<ILayout> = ({
    children
}) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/header-logo.png" />
        </Head>
        <Header />
        <main id="page-wrap" className={styles.main}>
            {children}
        </main>

        <footer className={styles.footer}>
         <div>
          © 2022, Reviveups
         </div>
         <div className={styles.socialLinks}>
          <ul>
            <li className={styles.iconLink}>
              <Link href="https://www.instagram.com/">
                <a>
                  <div className={cx(styles.iconWrapper, styles.instagram)}>

                  </div>
                </a>
              </Link>
            </li>
            <li className={styles.iconLink}>
            <Link href="https://instagram.com/cellfitvn?igshid=YmMyMTA2M2Y=">
              <a>
                <div className={cx(styles.iconWrapper, styles.facebook)}>

                </div>
              </a>
            </Link>
            </li>
            <li className={styles.iconLink}>
            <Link href="https://www.youtube.com/CellFitVn">
              <a href="https://www.youtube.com/CellFitVn">
                <div className={cx(styles.iconWrapper, styles.youtube)}>

                </div>
              </a>
            </Link>
            </li>
            <li className={styles.iconLink}>
            <Link href="https://pin.it/1HEVhoc">
              <a>
                <div className={cx(styles.iconWrapper, styles.pinterest)}>

                </div>
              </a>
            </Link>
            </li>
          </ul>
         </div>
        </footer>
      </div>
    </>
  );
};

export default Layout;
