import Head from "next/head";
import Image from "next/image";
import cx from "classnames";

import { Header } from "../Homepage/Header/Header";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

interface ILayout {
    children: JSX.Element;
}

const Layout: React.FC<ILayout> = ({
    children
}) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main id="page-wrap" className={styles.main}>
            {children}
        </main>

        <footer className={styles.footer}>
         <div>
          © 2022, Reviveups
         </div>
         <div className={styles.socialLinks}>
          <ul>
            <li className={styles.iconLink}>
              <a href="https://www.instagram.com/">
                <div className={cx(styles.iconWrapper, styles.instagram)}>

                </div>
              </a>
            </li>
            <li className={styles.iconLink}>
              <a href="https://facebook.com/">
                <div className={cx(styles.iconWrapper, styles.facebook)}>

                </div>
              </a>
            </li>
            <li className={styles.iconLink}>
              <a href="https://www.youtube.com/">
                <div className={cx(styles.iconWrapper, styles.youtube)}>

                </div>
              </a>
            </li>
          </ul>
         </div>
        </footer>
      </div>
    </>
  );
};

export default Layout;
